.github/workflows/auto-add-to-project.yml

Create an action that automatically adds all issues and pull requests to the main project board. This is done so team members don't have to manually add each issue to the project.
Closes #30

chore: add action for auto-adding issues and PRs to the project

---

frontend/src/App.jsx
frontend/src/components/Header.jsx
frontend/src/components/LoginForm.jsx
frontend/src/pages/LoginPage.jsx

- Adds `/login` page.
- Adds login form. (_Login_ action is still a placeholder, but non-empty user and at least 8 characters password need to be entered.)
- Adds modal displaying login form afer clicking the _Login_ button in header.
- Some styling borrowed from daisyUI (https://daisyui.com/components/input/, https://daisyui.com/components/button/, https://daisyui.com/components/modal/). Otherwise styling did not get any attention and it can be changed to whatever is necessary.
Ref: #20

feat: login placeholders

---

frontend/src/components/IdeaFormSection.jsx
frontend/src/hooks/useApi.js

- Refactors using fetch to separate hook.
- This is attempt to simplify using fetching and sending request to backend.
- Additionally it gives ability to attach headers, that are required, to each request, in a single place. Instead of doing it manually whenever `fetch` would be used.

refactor: extract fetching to useApi hook

---

README.md

Changing from `react-helmet-async` to `@dr.pogodin/react-helmet` means the dependency list has changed; this change explains the necessity for rebuilding the list of dependencies.

docs: update README after removing a legacy library

---

frontend/src/user/UserProvider.jsx

- Response from the refresh was getting lost, instead error which was being caught, was due to attempt of getting `json` from the initial response.

fix: throw when refresh fails

---

backend/src/api/routes/users.py
backend/src/models.py

- Api returns more info about user for the admin user listing.
- To be specific:
https://github.com/freeCodeCamp-2025-Summer-Hackathon/mint-syntax/blob/d7ddede8828f416fa50278dab9a33301adb62135/backend/src/models.py#L15-L22

chore: return more data for admin user listing

---

frontend/src/styles.css

The changes I made explicitly override the browser's default dark mode behavior for input fields, text areas, and select elements, ensuring they remain in our light color scheme. This was done to address the issue of inconsistent styling when a full dark mode feature hasn't still implemented.
Closes #178

fix: dark mode issue

---

frontend/src/components/Header.jsx

- When _Login_ button is clicked - dialog is shown.
- Button still has link to the `/login`, so it can be opened in new window, and/or copied.

chore: add link to login button

---

backend/src/api/routes/me.py
backend/src/api/routes/users.py
backend/src/models.py

- Separates admin user edit from user... user edit.
- Admin is able to edit `is_active` or `is_admin`, but user is not.
- Admin user edit uses PATCH `/users/{id}`, User user edit uses PATCH `/me`.

chore: separate admin user edit from user edit

---

backend/src/database.py

- Returns HTTP 503 when mongodb is not running.
- Might address #121

chore: return 503 when mongodb is not running

---

backend/src/api/routes/me.py

- Verifies `old_password` only when `old_password` and `new_password` are non-empty. This includes the non-included in request default `None`, and included empty string, when password is not changed in form.
- Ref https://github.com/freeCodeCamp-2025-Summer-Hackathon/mint-syntax/pull/200#issuecomment-3124715514

fix: verify old password only when non-empty

---

backend/src/api/routes/me.py

- Always verify `old_password`, when `new_password` is submitted.
- If `old_password` is _falsy_ - either `None` or empty string -> raise `403`.
- If `old_password` is valid -> raise `403`.

fix: verify old_password when new_password is submitted

---

backend/src/api/routes/me.py

- Couple changes to backend routes, to limit automatic redirects (HTTP `307`).
- Routes are:
- `/me` for GET and PATCH, but
- `/me/ideas/` for /me ideas

chore: unify /me routes to prevent redirects

---

frontend/eslint.config.js
frontend/src/components/ErrorBoundary.jsx
frontend/src/components/Footer.jsx
frontend/src/components/LoginForm.jsx
frontend/src/components/RegisterForm.jsx
frontend/src/pages/HelpPage.jsx
frontend/src/pages/LogoutPage.jsx
frontend/src/pages/MeEditPage.jsx
frontend/src/pages/MePage.jsx

- Well, this is awkward.
- Enable react specific eslint rules.
- Other changes are fixing the issues.
- Feature referred in `react/prop-types` is depreciated in React 19, so rule needs to be disabled.

chore: enable eslint react plugin rules

---

frontend/eslint.config.js
frontend/src/App.jsx

- Correctly shows unused `React` import in ESLint.

fix: detect unused React import

---

frontend/src/App.jsx
frontend/src/components/EnsureAdmin.jsx
frontend/src/components/EnsureLogin.jsx
frontend/src/components/Header.jsx
frontend/src/pages/LogoutPage.jsx
frontend/src/pages/MeEditPage.jsx
frontend/src/pages/MePage.jsx
frontend/src/pages/UserAddPage.jsx
frontend/src/pages/UserEditPage.jsx
frontend/src/pages/UserPage.jsx
frontend/src/pages/UsersPage.jsx
frontend/src/utils/wrapWith.jsx

- `EnsureAdmin` _ensures_ user is admin, before rendering _children_.
- `EnsureLogin` _ensures_ user is logged in, before rendering _children_.
- `EnsureAdmin` uses `EnsureLogin` internally.
- If not logged in user tries to access page requiring being logged in, or being admin, they will be redirected to login, with back-redirect to the accessed page.
- `wrapWith` is little helper to wrap `EnsureAdmin` or `EnsureLogin` around element.
- If logged in user accesses `/logout`, there's button to logout.

chore: wrapper to ensure certain userState

---

frontend/src/components/Pagination.jsx

- Going to the next page button (`>`) was still enabled on the last page.

fix: pagination < and > boundaries

---

frontend/src/components/IdeasList.jsx

- Ie. there were `2` pages of ideas. If one would manually visit url for page `3` or higher, there would be _no ideas text_ displayed, and no pagination.
- Now there's no _no ideas text_, and pagination is displayed.

fix: display pagination, if page number depleted ideas

---

backend/src/auth.py

- Second value in the tuple returned by `verify_and_update_password` (and `password_context.verify_and_update`) is `None`, if new hashing is not required, or already new hash, if new hash is needed.

chore: skip obsolete hashing

---

backend/tests/data_sample.py
backend/tests/test_auth.py

- Tests for `get_current_user`, `get_current_active_user`, `get_current_active_admin`, and `refresh_access_token`.
- Tests for `get_current_active_admin` are using couple cases (disabled users) that normally wouldn't  reach this function. Due to how FastAPI uses dependencies, `get_current_active_admin` can be reached only after `get_current_active_user`. So for disabled user exception, due to being inactive would be raised first. However, if any disabled, non-admin would manage to get to the `get_current_active_admin`, they'd still receive error due to not being admin.

test: remaining functions in `src.auth`

---

backend/src/config.py
backend/tests/api/test_ideas.py
backend/tests/api/test_util.py
backend/tests/conftest.py
backend/tests/data_sample.py
backend/tests/test_auth.py
backend/tests/test_config.py
sample.env

- For tests relying on real mongodb.
- For development `MONGODB_TEST_URI` env variable can be the same as the non-test. Fixture is supposed to clean-up data that's added.
- To easily differentiate, and avoid conflicts `test_` and `Test_` prefixes were added.

chore: real_db pytest fixture

---

.github/workflows/ci-backend.yml
backend/pyproject.toml

- Current idea is to run unit tests with `pytest -m "not integration"`, and integration tests with `pytest -m integration`.

chore: pytest integration marker

---

backend/tests/data_sample.py
backend/tests/test_auth.py
backend/tests/util.py

- Using _normal_ hashing when creating users for tests unrelated to hashes, is a bit time wasteful.

chore: reuse pre-computed hashes in tests

---

backend/src/api/routes/me.py
backend/src/api/routes/users.py
backend/src/models.py
backend/tests/api/routes/test_me.py

- Moves `hashed_password` out of the user input model. It was being updated if request contained `hashed_password`.

fix: rogue `hashed_password` updates

---

backend/src/api/routes/me.py
backend/src/api/routes/users.py
backend/src/models.py
backend/tests/api/routes/test_me.py

- This might sound a bit mouthful. There might be somewhere better terms for it, I'm not sure.
- `name` is optional in a sense - it doesn't need to be included in the request. In such case it will have default `None` value for a while and then it will be ignored when updating.
- However if `name` is included, but it's empty (string: `''`), that's an error.
- On the other hand `new_password` is optional - doesn't need to be included in the request. But it also can be included and empty - `''`, in both cases password should not be updated.
- Very possible it will be further changed to make it

fix: field requiring non-empty if included

---

backend/ruff.toml
backend/tests/api/routes/test_ideas.py
backend/tests/api/routes/test_users.py
backend/tests/api/test_ideas.py
backend/tests/api/test_routes.py
backend/tests/api/test_util.py
backend/tests/conftest.py
backend/tests/test_auth.py
backend/tests/test_csrf.py

- Just a bit of consistent style enforcing by ruff for pytest tests.

chore: enable ruff flake8-pytest-style rules for pytest

---

backend/src/api/ideas.py
backend/src/models.py
backend/tests/api/routes/test_ideas.py
backend/tests/api/routes/test_me.py
backend/tests/api/routes/test_users.py

- Datetimes for Idea
- Couple adjustments to datetime keeping. Currently any datetime that has no timezone info is assumed to be in the utc. This isn't perfect, but it's required since datetime from the database will not have timezone info.

feat: idea datetime
