- .github/PULL_REQUEST_TEMPLATE.md
- Adds basic pull request template
> chore: add basic pull request template

- backend/src/api/main.py
- backend/src/api/routes/ideas.py
- backend/src/api/routes/users.py
- backend/src/main.py
- backend/src/models.py
- Models are very rough, but give something to start with.
- Any place that would need user_id is taking it from the request. It should be replaced later with id of the user that's logged in.
- Routes:
- Users:
- Creating
- Editing
- Viewing
- Listing
- Ideas:
- Creating
- Editing
- Deleting
- Viewing
- Listing
- Upvoting
- Downvoting
> feat: basic user & ideas routes

- .github/workflows/lint-backend.yml
> chore: add lint backend ruff action

- frontend/.prettierrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/index.css
- frontend/tailwind.config.js
- frontend/vite.config.js
Adds Tailwind CSS and DaisyUI to the list of dependencies - this solution is more reliable than using CDN, and should help speed up developing the userinterface.
> chore: add tailwind css daisy UI

- .github/workflows/lint-frontend.yml
- frontend/package.json
- Action linting and checking formatting of the frontend.
> chore: lint-frontend action

- backend/src/config.py
- frontend/vite.config.js
- sample.env
- Configures loading environment variables from `.env` file in frontend.
- Updates handling `.env` file in backend to ignore excessive variables.
> chore: load .env file in frontend

- backend/src/auth.py
- Default positional argument in `timedelta` is _days_.
> fix: default positional argument is not minutes

- frontend/vite.config.js
Server settings part doesn't seem to be needed after all. I was confused while using wrong page url.
> chore: remove vite server config

- frontend/src/components/HelpPage.jsx
- Makes easier to extend faq.
- To access `/help` in browser you might need #70.
- This is almost pure JS.
Ref: #65
> refactor: make faq easier to extend

- frontend/src/main.jsx
- `/help` page was not accessible
> fix: inaccessible routes

- backend/src/models.py
- frontend/src/App.jsx
- frontend/src/components/IdeaFormSection.jsx
- Changes `IdeaFormSection` to accept number of ideas to display.
- Loads ideas from the db.
> feat: display ideas from db

- sample.env
> chore: add CSRF_SECRET_KEY to sample.env

- backend/src/api/routes/users.py
- Small fix to correctly make `create_user` to depend on form.
> fix: add form dependency on route creating users

- frontend/src/components/LoginForm.jsx
- frontend/src/hooks/useApi.js
- frontend/src/pages/LoginPage.jsx
- frontend/src/user/UserProvider.jsx
- Currently for login is used session/state, what makes it a bit fuzzy (try opening two tabs).
- Otherwise login/logout should be functional.
> feat: frontend login

- frontend/src/components/Footer.jsx
- frontend/src/components/IdeaSubmissionForm.jsx
- frontend/src/components/LandingPageContent.jsx
Remove not needed imports in components.
Closes #63
> fix: remove unused imports.

- frontend/src/components/Header.jsx
> fix: bug at relative navbar links

- backend/src/api/routes/ideas.py
- frontend/src/App.jsx
- frontend/src/components/IdeaFormSection.jsx
- Sorting of the ideas.
- Supports _trending_ sorting - by number of upvotes. Used on landing page.
- By default for sorting is used name of the idea.
> feat: ideas sorting

- frontend/src/pages/Ideas/IdeaPage.jsx
- Displays idea data loaded from api.
- Other than upvotes/downvotes stats, styling and data presentation is non-existing.
> feat: load idea data from api

- frontend/src/components/IdeaSubmissionForm.jsx
- frontend/src/user/UserProvider.jsx
- Adds creating ideas from frontend.
- After success redirects to `/ideas/{new_id_of_the_idea}`.
- Idea category is commented out.
- Fixes bug with saving access token, which revealed itself during implementing this.
Closes #118
> feat: submit idea

- frontend/package-lock.json
> chore: update package-lock

- frontend/src/App.jsx
- frontend/src/components/IdeaFormSection.jsx
- frontend/src/pages/Ideas/IdeasPage.jsx
- frontend/src/pages/LandingPage.jsx
- frontend/src/styles.css
Generalize IdeaFormSection CSS class names and remove unrelated styles.
Closes #112
> feat: separate Ideas listing from the header in IdeaFormSection

- frontend/src/components/IdeaFormSection.jsx
- I keep forgetting JS considers empty array as _truthy_.
> fix: correct loading indication condition

- frontend/src/components/IdeaSubmissionForm.jsx
- Adds tooltip, when not logged and hovering over the button to create idea.
> feat: tooltip to login when creating idea

- frontend/src/components/IdeasList.jsx
- frontend/src/pages/Ideas/IdeasPage.jsx
> fix: renamed IdeaFormSection to IdeasList

- frontend/src/pages/Ideas/IdeaPage.jsx
The updates to the styling of the IdeaPage.jsx
Closes #18
> refactor: IdeaPage

- frontend/src/components/VoteButtons.jsx
- frontend/src/styles.css
> refactor: new vote buttons

- frontend/src/components/IdeaSubmissionForm.jsx
- frontend/src/components/RegisterForm.jsx
> chore: add required field indicators to Idea Submission Form

- frontend/src/components/RegisterForm.jsx
- frontend/src/styles.css
+ by adjusting form-group div
Closes #160
> fix: resolve red star and input field misalignment

- frontend/src/App.jsx
- frontend/src/pages/UsersPage.jsx
> feat: add admin-only listing of all users scope: frontend

- README.md
+ fix some minor typos
Closes #179
> chore: add seeding script usage to the README.md

- frontend/src/hooks/useApi.js
> fix: default destructured parameter

- frontend/src/hooks/useApi.js
- frontend/src/user/UserProvider.jsx
- frontend/src/user/utils.js
- frontend/src/utils/apiUrl.js
- `UserProvider` was updating `access_token`, but `useApi` did not.
- Unifies that with separate util functions.
> fix: refresh access token

- backend/src/api/routes/users.py
- Backend `/users/{id}/ideas` route for admin view of user ideas.
> feat: backend admin view of user ideas

- backend/src/api/routes/users.py
- backend/src/models.py
- Adds `/users/add` to the backend for admin user creation.
> chore: separate user register from admin user creation

- frontend/src/App.jsx
- frontend/src/components/Header.jsx
- frontend/src/pages/UserAddPage.jsx
+ new pages/UserAddPage.jsx
+ updated Header.jsx
+ updated App.jsx
Closes #163
> feat: add admin-only page to create new users

- README.md
- Included local- and cloud setup instructions
- Added links to offical tutorials for reference
- Tried to adapt to existing writing style as much as possible.
Closes #197
> docs:database-setup-instructions

- frontend/src/components/IdeasList.jsx
- frontend/src/pages/LandingPage.jsx
> refactor: move "Explore All Ideas" under the "Vote on Current Ideas

- backend/src/models.py
- Adds basic constraints in models, for strings that are used as an input from user.
> chore: add basic constraints to input strings

- frontend/src/components/RegisterForm.jsx
> fix: remove '!isValid' argument from the button in 'RegisterForm

- frontend/src/components/Header.jsx
- frontend/src/components/ScrollToHashElement.jsx
- Referenced gikf's suggested solution
- Created component ScrollToHashElement.jsx
- Imported ScrollToHashElement compoonent in Header.jsx
- Refactored remaining two anchor tags to Link Components
- Manually tested that link components work as intended
Closes #60
> refactor: Navbar Links

- frontend/src/pages/UsersPage.jsx
Now the clickable area of the link is made larger, while the View Ideas button remains separate.
Closes #186
> fix: Users list - link to individual user

- frontend/src/components/IdeaListItem.jsx
- frontend/src/components/VoteButtons.jsx
- frontend/src/pages/Ideas/IdeaPage.jsx
- Improved indication whether user voted on idea.
- Improved stability of toggling upvote <-> downvote.
> chore: improve voting indication

- frontend/src/components/IdeaSubmissionForm.jsx
- frontend/src/components/LoginForm.jsx
- frontend/src/components/RegisterForm.jsx
- frontend/src/components/VoteButtons.jsx
- frontend/src/hooks/useApi.js
- frontend/src/pages/Ideas/IdeaEditPage.jsx
- frontend/src/pages/MeEditPage.jsx
- frontend/src/pages/UserAddPage.jsx
- frontend/src/pages/UserEditPage.jsx
- frontend/src/pages/UserPage.jsx
- Wraps sending data to api into two functions
- `sendAsJson` accepts JS object (and path and additional fetch options), sends it as JSON.
- `sendFormData` accepts JS object with form ref attribute (`formRef`) or `FormData` object attribute (`formData`) (and path and additional fetch options), sends it as form data.
> refactor: useApi send data

- frontend/src/components/Header.jsx
- Refactors user (and admin) menu links.
> refactor: user menu links

- frontend/eslint.config.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Header.jsx
- frontend/src/components/IdeasList.jsx
- frontend/src/components/Pagination.jsx
- frontend/src/pages/ForgotPassword.jsx
- frontend/src/pages/HelpPage.jsx
- frontend/src/pages/UserPage.jsx
- Adds eslint-plugin-jsx-a11y - https://github.com/jsx-eslint/eslint-plugin-jsx-a11y to detect part of the accessibility issues.
> chore: add eslint-plugin-jsx-a11y

- frontend/eslint.config.js
- frontend/src/components/LoginForm.jsx
- Apparently `<>` was not considered by default.
> fix: add key prop to rendered elements

- backend/src/api/routes/auth.py
- backend/src/api/routes/users.py
- backend/src/auth.py
- frontend/src/components/RegisterForm.jsx
- Makes api to return the same data when registering and logging in.
- After registering, user is logged in.
Closes #244
> feat: auto-login after registering

- frontend/src/App.jsx
- `/page/:page` part wasn't a child of `:id/ideas`
> fix: /users/:id/ideas/page/:page route

- backend/src/api/routes/me.py
- Adds sorting by name for /me/ideas
> chore: sort /me/ideas ideas by name

- backend/src/api/ideas.py
- backend/src/api/routes/ideas.py
- backend/src/api/routes/me.py
- backend/src/api/routes/users.py
- backend/src/api/util.py
- Bit of shuffling things around to reduce repetitions surrounding _ideas_ in the api.
> refactor: reduce api ideas repetitions

- backend/src/auth.py
- Refactors slightly two functions using identical code.
> refactor: extract decode_jwt function

- .github/workflows/ci-backend.yml
- .github/workflows/ci-frontend.yml
> fix: copy .env file for CI

- backend/tests/api/test_util.py
- backend/tests/conftest.py
- backend/tests/data_sample.py
- Moves sample data to separate file.
- Moves mock db to `conftest.py`.
> refactor: move mock db and sample data

- backend/tests/test_auth.py
> test: verify password

- backend/tests/conftest.py
- backend/tests/data_sample.py
- backend/tests/test_auth.py
- Test `authenticate_user` from `backend/src/auth.py`.
> test: `authenticate_user`

- backend/tests/conftest.py
- backend/tests/test_auth.py
> chore: simplify checking expected call

- backend/tests/test_auth.py
- Ref https://github.com/freeCodeCamp-2025-Summer-Hackathon/mint-syntax/actions/runs/17289741029/job/49074082284
> fix: missing import

- backend/src/auth.py
- backend/tests/test_auth.py
- Tests for `decode_token`.
- Fixtures are a bit all over the place
> test: `decode_token`

- backend/src/api/dependencies.py
- backend/src/api/routes/ideas.py
- backend/src/api/routes/users.py
- backend/src/api/util.py
- Refactors dependencies of objects obtained based on the `{id}` in the url patch.
- It's almost like magic.
> refactor: patch dependencies

- frontend/src/pages/Ideas/IdeaPage.jsx
- Fixes errors when accessed idea id doesn't exist.
> fix: handling non-existing idea id

- backend/src/api/dependencies.py
- backend/src/api/routes/ideas.py
- backend/src/api/routes/me.py
- backend/src/api/routes/users.py
- Standardizing pagination parameters.
> refactor: `PaginationParams`

- backend/tests/conftest.py
- Use `save_all` for batch saving.
> refactor: replace individual `save` with `save_all`

- backend/src/models.py
- Some of the constraints were not enforced. Ie. max length of the `NonEmptyMax255CharsString` was seemingly ignored (but minimum length was enforced 🤷‍♂️).
> fix: field constraints

- backend/src/api/ideas.py
- backend/src/api/routes/users.py
- Pydantic has built-in feature to deal with what we were doing by hand.
> chore: use `TypeAdapter` for list items validation

- backend/tests/api/conftest.py
- backend/tests/api/routes/test_ideas.py
- backend/tests/api/routes/test_me.py
- `/ideas/{id}/downvote`
- `/ideas/{id}/upvote`
> test: idea vote routes

- backend/tests/api/routes/test_ideas.py
> test: `/ideas/count` route

- backend/tests/api/routes/test_ideas.py
> test: `/ideas/{id}` route

- backend/tests/api/routes/test_ideas.py
> test: delete idea route

- backend/tests/api/conftest.py
- backend/tests/api/routes/test_ideas.py
- backend/tests/api/routes/test_me.py
- backend/tests/api/routes/test_users.py
- backend/tests/util.py
- Slight simplification of idea and user setup.
> refactor: idea and user setup

- .pre-commit-config.yaml
- backend/tests/api/routes/test_me.py
- Should have done it earlier.
> tools: reject commit if `@pytest.mark.only` is in file

- backend/tests/api/routes/test_auth.py
> test: `/auth` route

- backend/tests/api/conftest.py
- backend/tests/api/routes/test_auth.py
- backend/tests/conftest.py
> test: `/refresh` route
